apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nr-ue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-nr-ue
  template:
    metadata:
      labels:
        app: oai-nr-ue
    spec:
      containers:
      - name: oai-nr-ue
        image: oaisoftwarealliance/oai-nr-ue:develop
        securityContext:
          privileged: true
        env:
        - name: RFSIMULATOR
          value: "oai_gnb"
        - name: FULL_IMSI
          value: "208990100001100"
        - name: FULL_KEY
          value: "fec86ba6eb707ed08905757b1bb44b8f"
        - name: OPC
          value: "C42449363BBAD02B66D16BC975D77CC1"
        - name: DNN
          value: "oai"
        - name: NSSAI_SST
          value: "1"
        - name: NSSAI_SD
          value: "1"
        - name: USE_ADDITIONAL_OPTIONS
          value: "-E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod"
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - "pgrep nr-uesoftmodem"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - "pgrep nr-uesoftmodem"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: oai-nr-ue
spec:
  selector:
    app: oai-nr-ue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
