apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nrf
  labels:
    app: oai-nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-nrf
  template:
    metadata:
      labels:
        app: oai-nrf
    spec:
      containers:
        - name: oai-nrf
          image: oaisoftwarealliance/oai-nrf:latest
          env:
            - name: NRF_INTERFACE_NAME_FOR_SBI
              value: eth0
            - name: NRF_INTERFACE_PORT_FOR_SBI
              value: "80"
            - name: NRF_INTERFACE_HTTP2_PORT_FOR_SBI
              value: "9090"
            - name: NRF_API_VERSION
              value: v1
            - name: INSTANCE
              value: "0"
            - name: PID_DIRECTORY
              value: /var/run
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: oai-nrf
  labels:
    app: oai-nrf
spec:
  selector:
    app: oai-nrf
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP

