apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-spgwu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-spgwu
  template:
    metadata:
      labels:
        app: oai-spgwu
    spec:
      containers:
      - name: oai-spgwu
        image: oaisoftwarealliance/oai-spgwu-tiny:latest
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
            drop:
            - ALL
          privileged: true
        env:
        - name: TZ
          value: "Europe/Paris"
        - name: PID_DIRECTORY
          value: "/var/run"
        - name: SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP
          value: "eth0"
        - name: SGW_INTERFACE_NAME_FOR_SX
          value: "eth0"
        - name: PGW_INTERFACE_NAME_FOR_SGI
          value: "eth0"
        - name: NETWORK_UE_NAT_OPTION
          value: "yes"
        - name: NETWORK_UE_IP
          value: "12.1.1.0/24"
        - name: SPGWC0_IP_ADDRESS
          value: "192.168.71.133"
        - name: BYPASS_UL_PFCP_RULES
          value: "no"
        - name: MCC
          value: "208"
        - name: MNC
          value: "99"
        - name: MNC03
          value: "099"
        - name: TAC
          value: "1"
        - name: GTP_EXTENSION_HEADER_PRESENT
          value: "yes"
        - name: GW_ID
          value: "1"
        - name: REALM
          value: "openairinterface.org"
        - name: ENABLE_5G_FEATURES
          value: "yes"
        - name: REGISTER_NRF
          value: "yes"
        - name: USE_FQDN_NRF
          value: "yes"
        - name: UPF_FQDN_5G
          value: "oai-spgwu"
        - name: NRF_IPV4_ADDRESS
          value: "192.168.71.130"
        - name: NRF_PORT
          value: "80"
        - name: NRF_API_VERSION
          value: "v1"
        - name: NRF_FQDN
          value: "oai-nrf"
        - name: NSSAI_SST_0
          value: "1"
        - name: NSSAI_SD_0
          value: "1"
        - name: DNN_0
          value: "oai"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: spgwu-healthcheck
          mountPath: /openair-spgwu-tiny/bin/spgwu-healthcheck.sh
          subPath: spgwu-healthcheck.sh
      volumes:
      - name: spgwu-healthcheck
        configMap:
          name: spgwu-healthcheck
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spgwu-healthcheck
data:
  spgwu-healthcheck.sh: |
    #!/bin/bash
    /bin/bash -c "/openair-spgwu-tiny/bin/spgwu-healthcheck.sh"
---
apiVersion: v1
kind: Service
metadata:
  name: oai-spgwu
spec:
  selector:
    app: oai-spgwu
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spgwu-network-policy
spec:
  podSelector:
    matchLabels:
      app: oai-spgwu
  ingress:
  - from:
    - ipBlock:
        cidr: 192.168.71.0/24
    - ipBlock:
        cidr: 192.168.72.0/24
    ports:
    - protocol: TCP
      port: 80

