apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-gnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-gnb
  template:
    metadata:
      labels:
        app: oai-gnb
    spec:
      containers:
      - name: oai-gnb
        image: oaisoftwarealliance/oai-gnb:develop
        securityContext:
          privileged: true
        env:
        - name: RFSIMULATOR
          value: "server"
        - name: USE_SA_TDD_MONO
          value: "yes"
        - name: GNB_NAME
          value: "gnb-rfsim"
        - name: TAC
          value: "1"
        - name: MCC
          value: "208"
        - name: MNC
          value: "99"
        - name: MNC_LENGTH
          value: "2"
        - name: NSSAI_SST
          value: "1"
        - name: NSSAI_SD0
          value: "1"
        - name: NSSAI_SD1
          value: "112233"
        - name: AMF_IP_ADDRESS
          value: "192.168.71.132"
        - name: GNB_NGA_IF_NAME
          value: "eth0"
        - name: GNB_NGA_IP_ADDRESS
          value: "192.168.71.136"
        - name: GNB_NGU_IF_NAME
          value: "eth0"
        - name: GNB_NGU_IP_ADDRESS
          value: "192.168.71.136"
        - name: USE_ADDITIONAL_OPTIONS
          value: "--sa -E --rfsim"
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - "pgrep nr-softmodem"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - "pgrep nr-softmodem"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: oai-gnb
spec:
  selector:
    app: oai-gnb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gnb-network-policy
spec:
  podSelector:
    matchLabels:
      app: oai-gnb
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: oai-ext-dn
    ports:
    - protocol: TCP
      port: 80

